In [0]:
from google.colab import drive
drive.mount('/content/gdrive')

In [0]:
import pandas as pd 
import nltk
#nltk.download('stopwords')  #Uncomment if stopwords aren't already dowloaded 
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer 
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score



In [0]:
dataset = pd.read_json("gdrive/My Drive/Colab Notebooks/dataset.json",lines = True)

In [56]:
dataset.head()

article_link  \
0  https://www.huffingtonpost.com/entry/versace-b...   
1  https://www.huffingtonpost.com/entry/roseanne-...   
2  https://local.theonion.com/mom-starting-to-fea...   
3  https://politics.theonion.com/boehner-just-wan...   
4  https://www.huffingtonpost.com/entry/jk-rowlin...   

                                            headline  is_sarcastic  
0  former versace store clerk sues over secret 'b...             0  
1  the 'roseanne' revival catches up to our thorn...             0  
2  mom starting to fear son's web series closest ...             1  
3  boehner just wants wife to listen, not come up...             1  
4  j.k. rowling wishes snape happy birthday in th...             0

In [57]:
try:
    dataset = dataset.drop("article_link", axis = 1)
    
    X = dataset.headline
    y = dataset.is_sarcastic
    corpus = []
    print("The process will take time be patient!")
    for i in range(0,len(X)):
        review = re.sub('[^a-zA-Z]', ' ', X[i])
        review = review.lower()
        review = review.split()
        ps = PorterStemmer()
        review = [ps.stem(word) for word in review]
        review = ' '.join(review)
        corpus.append(review)

except Exception as e:
       print(e)


The process will take time be patient!


In [0]:
vectorizer = CountVectorizer()  
X = vectorizer.fit_transform(corpus).toarray()

#tfidf = TfidfVectorizer(max_features = 2000,stop)  
#X = tfidf.fit_transform(corpus).toarray()

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=0)


In [60]:
print(len(X_train[2]))

16814


In [15]:
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()

classifier.fit(X_train, y_train) 
y_pred = classifier.predict(X_test)  
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))  
print(accuracy_score(y_test, y_pred))

[[2531  476]
 [ 578 1757]]
              precision    recall  f1-score   support

           0       0.81      0.84      0.83      3007
           1       0.79      0.75      0.77      2335

   micro avg       0.80      0.80      0.80      5342
   macro avg       0.80      0.80      0.80      5342
weighted avg       0.80      0.80      0.80      5342

0.8026956196181205


In [13]:
classifier = RandomForestClassifier(n_estimators=5, random_state=0)  
classifier.fit(X_train, y_train) 
y_pred = classifier.predict(X_test)  
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))  
print(accuracy_score(y_test, y_pred))

[[2455  552]
 [ 647 1688]]
              precision    recall  f1-score   support

           0       0.79      0.82      0.80      3007
           1       0.75      0.72      0.74      2335

   micro avg       0.78      0.78      0.78      5342
   macro avg       0.77      0.77      0.77      5342
weighted avg       0.77      0.78      0.77      5342

0.7755522276301011


In [0]:

# Fitting Naive Bayes to the Training set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

print(classification_report(y_test,y_pred))  
print(accuracy_score(y_test, y_pred))


              precision    recall  f1-score   support

           0       0.82      0.63      0.71      3007
           1       0.63      0.82      0.71      2335

   micro avg       0.71      0.71      0.71      5342
   macro avg       0.73      0.73      0.71      5342
weighted avg       0.74      0.71      0.71      5342

0.7141520029951329


In [0]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 123)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))  
print(accuracy_score(y_test, y_pred))

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


[[2533  474]
 [ 539 1796]]
              precision    recall  f1-score   support

           0       0.82      0.84      0.83      3007
           1       0.79      0.77      0.78      2335

   micro avg       0.81      0.81      0.81      5342
   macro avg       0.81      0.81      0.81      5342
weighted avg       0.81      0.81      0.81      5342

0.8103706476974916


In [0]:
from sklearn.svm import LinearSVC

classifier = LinearSVC()


classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))  
print(accuracy_score(y_test, y_pred))

[[2506  501]
 [ 543 1792]]
              precision    recall  f1-score   support

           0       0.82      0.83      0.83      3007
           1       0.78      0.77      0.77      2335

   micro avg       0.80      0.80      0.80      5342
   macro avg       0.80      0.80      0.80      5342
weighted avg       0.80      0.80      0.80      5342

0.8045675776862599


In [44]:

from keras.models import Sequential
from keras.layers import Dense
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(output_dim = 500, init = 'uniform', activation = 'relu', input_dim = len(X_train[1])))

# Adding the second hidden layer
classifier.add(Dense(output_dim = 500, init = 'uniform', activation = 'relu'))

#Adding the third hidden layer
classifier.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, nb_epoch = 100)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:8: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=17017, units=500, kernel_initializer="uniform")`
  
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:11: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=500, kernel_initializer="uniform")`
  # This is added back by InteractiveShellApp.init_path()
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:14: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:20: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.


Epoch 1/100
 8220/21367 [==========>...................] - ETA: 21s - loss: 0.4621 - acc: 0.7808

KeyboardInterrupt: ignored

In [30]:
y_pred = classifier.predict_classes(X_test)
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))  
print(accuracy_score(y_test, y_pred))

[[2512  495]
 [ 524 1811]]
              precision    recall  f1-score   support

           0       0.83      0.84      0.83      3007
           1       0.79      0.78      0.78      2335

   micro avg       0.81      0.81      0.81      5342
   macro avg       0.81      0.81      0.81      5342
weighted avg       0.81      0.81      0.81      5342

0.809247472856608


In [61]:


from keras.models import Sequential
from keras.layers import Dense
from keras import regularizers
from keras.optimizers import RMSprop

# Initialising the ANN
classifier_reg = Sequential()

# Adding the input layer and the first hidden layer
classifier_reg.add(Dense(output_dim = 500, init = 'uniform', activation = 'relu', input_dim = len(X_train[1]),kernel_regularizer=regularizers.l2(0.00005)))


# Adding the second hidden layer
classifier_reg.add(Dense(output_dim = 750, init = 'uniform', activation = 'relu',kernel_regularizer=regularizers.l2(0.00005)))

# Adding the third hidden layer
classifier_reg.add(Dense(output_dim = 750, init = 'uniform', activation = 'relu',kernel_regularizer=regularizers.l2(0.00005)))

#Adding the third hidden layer
classifier_reg.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier_reg.compile(optimizer = RMSprop(), loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier_reg.fit(X_train, y_train, batch_size = 70, nb_epoch = 3)

y_pred = classifier_reg.predict_classes(X_test)

print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))  
print(accuracy_score(y_test, y_pred))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:12: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=16814, kernel_regularizer=<keras.reg..., units=500, kernel_initializer="uniform")`
  if sys.path[0] == '':
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:16: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", kernel_regularizer=<keras.reg..., units=750, kernel_initializer="uniform")`
  app.launch_new_instance()
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:19: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", kernel_regularizer=<keras.reg..., units=750, kernel_initializer="uniform")`
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:22: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:28:

Epoch 1/3
22702/22702 [==============================] - 10s 420us/step - loss: 0.5450 - acc: 0.7512
Epoch 2/3
22702/22702 [==============================] - 7s 329us/step - loss: 0.4344 - acc: 0.8096
Epoch 3/3
22702/22702 [==============================] - 8s 333us/step - loss: 0.4064 - acc: 0.8237
[[1932  328]
 [ 508 1239]]
              precision    recall  f1-score   support

           0       0.79      0.85      0.82      2260
           1       0.79      0.71      0.75      1747

   micro avg       0.79      0.79      0.79      4007
   macro avg       0.79      0.78      0.78      4007
weighted avg       0.79      0.79      0.79      4007

0.7913651110556527


In [0]:
classifier_reg.save("regularizer.h5")

In [0]:
classifier.save("non regularizer.h5")